version: "3.9"
services:
  hygraph:
    image: mp4sini/hygraph:latest
    hostname: hygraph
    container_name: hygraph
    env_file:
      - ./../.env
    volumes:
      - "./../data:/hygraph/results"
    command:
      - /bin/bash
      - -c
      - |
        chmod +x scripts/run_evaluation.sh.sh
        chmod +x scripts/download_dataset.sh
        ./scripts/run_evaluation.sh.sh