version: "3.9"
services:
  aeong:
    image: mp4sini/aeong:latest
    hostname: aeong
    container_name: aeong
    env_file:
      - ./../.env  
    volumes:
      - ./../data/aeong:/home/AeonG/tests/results/aeong/
      - ./volumes/time_constraints_commit.yaml:/vol/time_constraints.yaml
      - ./volumes/queries/aeong:/home/AeonG/tests/results/temporal_query
    command:
      - /bin/bash
      - -c
      - |
        cp /vol/time_constraints.yaml /home/AeonG/tests/experiments/
        ./t_smarbench_test.sh
